### ISSUE TITLE
It fails for pre-release regarding semver specification

### ISSUE THREAD

**Issue by Ariel-Rodriguez** [unicorn-fail/version_compare#1]
http://semver.org/

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

```bash
./version_compare 1.0.0-rc.0 1.0.0
1
```

It is expected to return -1. Because 1.0.0-rc.0 is older than 1.0.0

I created a simplified semver compare in bash here: https://gist.github.com/Ariel-Rodriguez/9e3c2163f4644d7a389759b224bfe7f3

**Comment by markhalliwell** [comment]
> It is expected to return -1. Because 1.0.0-rc.0 is older than 1.0.0

That is because this tool is for http://semver.org/spec/v1.0.0.html, not the 2.0.0 spec. I've gone ahead and updated the README.md file accordingly (https://github.com/unicorn-fail/version_compare/commit/cc9817ecb3bbbe7f24b070261466d5abd384f7c3).

> I created a simplified semver compare in bash here

Your version uses `awk` which is [widely known](https://stackoverflow.com/a/24334941/1226717) to behave differently across various OS platforms (specially macOS).

Aside from using `printf` (which is safe in this context), this is a pure BASH solution which provides consistency across all *nix based platforms.
